#!/usr/bin/env python3
"""wikidistill — emit a "what changed this week" snapshot.

Walks `git log` over the last N days (default 7) to find changed wiki pages,
classifies them by frontmatter `type`, and writes a distill report at
`wiki/distill/YYYY-MM-DD.md`. Designed to run weekly so the operator can keep their
mental model fresh without re-reading the whole wiki.

Usage:
    python3 scripts/wikidistill.py            # weekly report, write to wiki/distill/<today>.md
    python3 scripts/wikidistill.py --days 30  # 30-day report (monthly)
    python3 scripts/wikidistill.py --stdout   # print to stdout instead of writing
    python3 scripts/wikidistill.py --since 2026-04-22  # explicit start date

Cadence guidance: weekly (every Monday, say) for routine "what's drifting"
catches; monthly for the bigger trend view; quarterly for state-of-the-union.

The report itself is `type: log` so it stays out of the Concepts / Syntheses
sections of `index.md` (which are auto-generated from frontmatter).
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from wikiutil import WIKI_ROOT, is_skipped, read_frontmatter  # noqa: E402

DISTILL_DIR = WIKI_ROOT / "distill"


def git(args: list[str]) -> str:
    return subprocess.check_output(["git", *args], text=True)


def changed_files(since: str) -> list[tuple[str, str]]:
    """Return [(status, path)] for files in wiki/ changed since `since` (YYYY-MM-DD)."""
    out = git([
        "log", f"--since={since}",
        "--name-status", "--pretty=format:",
        "--", "wiki/",
    ])
    rows = []
    for line in out.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        status = parts[0][0]  # A, M, D, R[100], etc.
        if status == "R":
            # Rename: status, old, new
            path = parts[2] if len(parts) >= 3 else parts[1]
        else:
            path = parts[1]
        rows.append((status, path))
    return rows


def classify(rows: list[tuple[str, str]]) -> dict:
    """Group: added/modified per type, plus deletions, plus assets."""
    seen = {}  # path -> (first_status, latest_status)
    for status, path in rows:
        if path not in seen:
            seen[path] = (status, status)
        else:
            seen[path] = (seen[path][0], status)
    return seen


def read_fm(path: Path) -> dict:
    if not path.exists():
        return {}
    return read_frontmatter(path.read_text(encoding="utf-8")) or {}


def lint_state() -> str:
    try:
        proc = subprocess.run(
            ["python3", "scripts/wikilint.py"],
            capture_output=True, text=True,
        )
    except FileNotFoundError:
        return "wikilint not available"
    # Last line of stderr is the summary
    summary = (proc.stderr or "").strip().splitlines()
    return summary[-1] if summary else "wikilint produced no output"


def render(since: dt.date, today: dt.date, changes: dict) -> str:
    by_type_added = defaultdict(list)
    by_type_modified = defaultdict(list)
    deleted = []
    asset_changes = []

    for path_str, (first, last) in changes.items():
        if path_str.startswith("wiki/assets/"):
            asset_changes.append((last, path_str))
            continue
        path = Path(path_str)
        if path.suffix != ".md":
            continue
        # Skip README.md and source-note markdown attachments — same rule as
        # wikilint and wikiindex (see wikiutil.is_skipped).
        if is_skipped(path):
            continue
        if last == "D":
            deleted.append(path_str)
            continue
        fm = read_fm(path)
        typ = fm.get("type", "(unknown)")
        added_in_window = (first == "A")
        if added_in_window:
            by_type_added[typ].append((path, fm))
        else:
            by_type_modified[typ].append((path, fm))

    days = (today - since).days
    if days >= 28:
        period = f"{days}-day"
    elif days >= 6:
        period = "weekly"
    else:
        period = f"{days}-day"

    lines = [
        "---",
        "type: log",
        f"tags: [wiki, distill, {period.replace(' ', '-')}]",
        f"created: {today.isoformat()}",
        f"updated: {today.isoformat()}",
        f'index-description: "{period} wiki distill: {len(changes)} files changed."',
        "---",
        "",
        f"# Wiki distill ({today.isoformat()})",
        "",
        f"Period: **{since.isoformat()} → {today.isoformat()}** ({days} days). "
        f"Auto-generated by `scripts/wikidistill.py`.",
        "",
        "## At a glance",
        "",
    ]

    n_added = sum(len(v) for v in by_type_added.values())
    n_modified = sum(len(v) for v in by_type_modified.values())
    summary_bits = [f"**{n_added} new pages**", f"**{n_modified} modified**"]
    if deleted:
        summary_bits.append(f"**{len(deleted)} deleted**")
    if asset_changes:
        summary_bits.append(f"**{len(asset_changes)} asset changes**")
    lines.append("- " + " · ".join(summary_bits))

    type_counts_added = Counter({t: len(v) for t, v in by_type_added.items()})
    if type_counts_added:
        lines.append(
            "- New by type: "
            + ", ".join(f"{n} {t}" for t, n in type_counts_added.most_common())
        )
    type_counts_mod = Counter({t: len(v) for t, v in by_type_modified.items()})
    if type_counts_mod:
        lines.append(
            "- Modified by type: "
            + ", ".join(f"{n} {t}" for t, n in type_counts_mod.most_common())
        )
    lines.append(f"- Lint state: `{lint_state()}`")
    lines.append("")

    def render_pages(pages: list[tuple[Path, dict]]) -> list[str]:
        out = []
        for p, fm in sorted(pages, key=lambda x: x[0].name.lower()):
            name = p.stem
            desc = fm.get("index-description")
            if desc:
                out.append(f"- [[{name}]] — {desc}")
            else:
                out.append(f"- [[{name}]]")
        return out

    type_order = ["entity", "concept", "synthesis", "decision", "source", "log", "index"]

    if any(by_type_added.values()):
        lines.append("## New pages")
        lines.append("")
        for t in type_order:
            if t in by_type_added:
                lines.append(f"### {t.capitalize()}")
                lines.extend(render_pages(by_type_added[t]))
                lines.append("")

    if any(by_type_modified.values()):
        lines.append("## Modified pages")
        lines.append("")
        for t in type_order:
            if t in by_type_modified:
                lines.append(f"### {t.capitalize()}")
                lines.extend(render_pages(by_type_modified[t]))
                lines.append("")

    if deleted:
        lines.append("## Deleted")
        lines.append("")
        for p in sorted(deleted):
            lines.append(f"- ~~{p}~~")
        lines.append("")

    if asset_changes:
        lines.append("## Asset changes")
        lines.append("")
        for last, p in sorted(asset_changes, key=lambda x: x[1]):
            verb = {"A": "added", "M": "modified", "D": "deleted"}.get(last, last)
            lines.append(f"- {verb}: `{p}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def latest_distill_date() -> dt.date | None:
    """Return the date encoded in the newest wiki/distill/YYYY-MM-DD.md filename, or None."""
    if not DISTILL_DIR.exists():
        return None
    candidates: list[dt.date] = []
    for p in DISTILL_DIR.glob("*.md"):
        if p.name == "README.md":
            continue
        try:
            candidates.append(dt.date.fromisoformat(p.stem))
        except ValueError:
            pass
    return max(candidates) if candidates else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=7)
    ap.add_argument("--since", help="explicit YYYY-MM-DD start; overrides --days")
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument(
        "--if-stale", action="store_true",
        help="No-op exit 0 if the most recent distill is younger than --days; "
             "otherwise produce a fresh distill. Used by /wikilint to auto-run on a 7-day cadence.",
    )
    args = ap.parse_args()

    today = dt.date.today()

    if args.if_stale:
        latest = latest_distill_date()
        if latest is not None and (today - latest).days < args.days:
            print(
                f"latest distill at wiki/distill/{latest}.md is {(today - latest).days}d old "
                f"(< {args.days}d threshold); skipping",
                file=sys.stderr,
            )
            return 0
        # If we're going to write, treat the previous distill as the lower bound
        # for "what changed" rather than the literal --days window. That way a
        # 10-day-late distill covers all 10 days, not just the trailing 7.
        if latest is not None:
            since = latest
        else:
            since = today - dt.timedelta(days=args.days)
    elif args.since:
        since = dt.date.fromisoformat(args.since)
    else:
        since = today - dt.timedelta(days=args.days)

    rows = changed_files(since.isoformat())
    if not rows:
        print(f"no wiki/ changes since {since.isoformat()}", file=sys.stderr)
        return 0
    changes = classify(rows)

    output = render(since, today, changes)

    if args.stdout:
        sys.stdout.write(output)
        return 0

    DISTILL_DIR.mkdir(parents=True, exist_ok=True)
    out_path = DISTILL_DIR / f"{today.isoformat()}.md"
    out_path.write_text(output, encoding="utf-8")
    print(f"wrote {out_path} ({len(changes)} files in window)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
